---
apiVersion: v1
kind: Service
metadata:
  name: grafana-blue
  labels:
    app: grafana-blue
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30013
    protocol: TCP
  selector:
    app: grafana-blue
