---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-blue-pvc
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

