---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    name: sonarqube
spec:
  type: NodePort
  ports:
    - name: sonarport
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    name: sonarqube-blue
status:
  loadBalancer: {}
