---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-green-pvc
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: jenkins-blue-pvc
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

