---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-green
  labels:
    app: jenkins-green
spec:
  type: NodePort
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: slave
      protocol: TCP
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins-green
status:
  loadBalancer: {}
