---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-green
  labels:
    app: grafana-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-green
  template:
    metadata:
      labels:
        app: grafana-green
    spec:
      containers:
      - image: grafana/grafana:5.4.3
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-green-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 472

