---
apiVersion: v1
kind: Service
metadata:
  name: grafana-green
  labels:
    app: grafana-green
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30015
  selector:
    app: grafana-green
