---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-green-pv
spec:
  storageClassName: csi-hostpath-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana-green"

