---
apiVersion: v1
kind: Service
metadata:
  name: sonatype-nexus-green
spec:
  type: NodePort
  ports:
    - name: sonatype
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30011
    - name: docker-rep
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30012
  selector:
    app: sonatype-nexus-green
    group: service
    statefulset.kubernetes.io/pod-name: sonatype-nexus-green-0
status:
  loadBalancer: {}