---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-nexus-blue-pvc
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

