---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonatype-nexus-blue-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-92e85a67:/sonatype-nexus-blue
