---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-nexus-blue-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
