---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonatype-nexus-blue
  labels:
    app: sonatype-nexus-blue
    group: service
spec:
  replicas: 1
  serviceName: sonatype-nexus-blue
  selector:
    matchLabels:
      app: sonatype-nexus-blue
  template:
    metadata:
      labels:
        app: sonatype-nexus-blue
        group: service
    spec:
      containers:
        - name: sonatype-nexus
          image: sonatype/nexus3:3.28.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MAX_HEAP
              value: "800m"
            - name: MIN_HEAP
              value: "300m"
          ports:
            - name: sonatype
              containerPort: 8081
              protocol: TCP
            - containerPort: 8123
              protocol: TCP
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
            - name: nexus-storage
              mountPath: /nexus-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: sonatype-nexus-blue-pvc
      securityContext:
        runAsUser: 200
        runAsGroup: 2000
        fsGroup: 2000
      schedulerName: default-scheduler
