---
apiVersion: v1
kind: Service
metadata:
  name: sonatype-nexus-blue
spec:
  type: NodePort
  ports:
    - name: sonatype
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30009
    - name: docker-rep
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30010
  selector:
    app: sonatype-nexus-blue
    group: service
    statefulset.kubernetes.io/pod-name: sonatype-nexus-blue-0
status:
  loadBalancer: {}
  