---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [plugins]
    enable_alpha = false
    app_tls_skip_verify_insecure = false
    # Enter a comma-separated list of plugin identifiers to identify plugins that are allowed to be loaded even if they lack a valid signature.
    allow_loading_unsigned_plugins = btplc-trend-box-panel,grafana-kubernetes-app,grafana-piechart-panel
    marketplace_url = https://grafana.com/grafana/plugins/
