---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-service
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30012
    protocol: TCP
  selector:
    app: grafana-blue
