---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-green
  labels:
    app: influxdb-green
    task: monitoring
spec:
  ports:
    - name: api
      port: 8086
      targetPort: 8086
      protocol: TCP
    - name: rpc
      port: 8088 
      targetPort: 8088
      protocol: TCP
  selector:
    name: influxdb-green
status:
  loadBalancer: {}
