---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins-service
spec:
  type: NodePort
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: slave
      protocol: TCP
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins-blue
status:
  loadBalancer: {}
