---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins-service
spec:
  type: NodePort
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
    - name: slave
      port: 50000
      protocol: TCP
  selector:
    app: jenkins-blue

