---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-blue-pv
spec:
  storageClassName: csi-hostpath-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb-blue"

