---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-green-pv
spec:
  storageClassName: csi-hostpath-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres-green"

