---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-green
  labels:
    name: sonarqube-green
spec:
  type: NodePort
  ports:
    - name: sonarqube-ui
      port: 9000
      targetPort: 9000
      nodePort: 30005
      protocol: TCP
  selector:
    name: sonarqube-green

