---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-green
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube-green
  template:
    metadata:
      name: sonarqube-green
      labels:
        name: sonarqube-green
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
      containers:
        - name: sonarqube-green
          image: sonarqube:8.5.1-community
          ports:
            - name: sonarqube
              containerPort: 9000
              protocol: TCP
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: sonar
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://postgres-green:5432/sonar
          resources:
            limits:
              memory: 2000Mi
            requests:
              memory: 2000Mi
          volumeMounts:
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions-green-pvc
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-green-pvc
