---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-blue-pvc
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
