---
apiVersion: v1
kind: Service
metadata:
  name: postgres-blue
  labels:
    name: postgres-blue
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgres-blue
  type: ClusterIP
status:
  loadBalancer: {}