---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-blue
  labels:
    name: sonarqube-blue
spec:
  type: NodePort
  ports:
    - name: sonarqube-ui
      port: 9000
      targetPort: 9000
      nodePort: 30004
      protocol: TCP
  selector:
    name: sonarqube-blue

