---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-blue
  labels:
    app: jenkins-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-blue
  template:
    metadata:
      labels:
        app: jenkins-blue
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins-blue
          image: vilvamani007/jenkins:2.235.5-lts-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50000
              protocol: TCP
          env:
          - name: JAVA_OPTS
            value: -Xmx2048m -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
          - name: jenkins
            mountPath: /var/jenkins_home
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: jenkins-blue-pvc
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
