---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-blue-pv
spec:
  storageClassName: csi-hostpath-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins-blue"
